<?php
/**
 * These defines may need to be updated when a new excel file is uploaded
 * adding an additional row pushes out all the references
 */
define('PC_EXCEL_SUMMARY' , 'c98:f104');
define('PC_EXCEL_PERIOD'  , 'd6');

define('PC_EXCEL_GROSS_LETTABLE_AREA'  , 'd82:e88');
define('PC_EXCEL_ASSET_VALUE'          , 'g82:h88');
define('PC_EXCEL_NET_OPERATING_INCOME' , 'j82:k88');

define('PC_EXCEL_JV'  , 'c109:d110');
define('PC_EXCEL_JVM' , 'g109:k120');

define('PC_EXCEL_AUS' , 'c4:k58');
define('PC_EXCEL_NZ'  , 'c62:k76');

define('PC_CONTROL_SHEET'  , 0);
define('PC_OVERVIEW_SHEET' , 1);

/**
 * Property parsing is flexible in the number of rows per table
 * it's shouldn't be neccessary to update the following defines
 */
define('COL_START'      , 'B');      // The first significant column in xlsx
define('COL_END'        , 'D');      // The last column in xlsx
define('COL_VISIBILITY' , 'I');      // The column that toggles visibility in xlsx

define('PC_CACHE_DIRNAME' , 'pccache');

require_once 'lib/PHPExcel/Classes/PHPExcel/IOFactory.php';
require_once 'lib/dompdf/dompdf_config.inc.php';
require_once 'lib/Parse.php';
require_once 'pc.menu.inc';


$css = <<<EOT
.portfolio table {
    width: 100%;
}
.portfolioheading,
.portfolio table th {
    background-color: black;
    color: white;
    padding: 13px 3px 1px 3px;
}
.portfolio table td {
    background-color: white;
}

.centretitle {
    background-color: black;
    color: white;
    padding: 13px 3px 1px 3px;
}

.charttitle {
    border-top: 1px solid black;
    padding-top:5px;
    padding-bottom:5px;
    border-bottom: 1px solid #808084;
		width: 215px;
}

.piechart {
    margin-top:10px;
}

.col3 {
    width:227px;
    float:left;
    margin-right:5px;
    margin-top:10px;
}

/* Set no border for r2d3 pie */
.noborder {
    stroke: white;
    stroke-width: 0;
}

EOT;

drupal_add_css( $css, 'inline');

// R2D3 makes d3 compatible with internet explorer
$mpath = base_path().drupal_get_path('module', 'pc');
$script = <<<EOT
<!--[if lte IE 8]><script src="$mpath/lib/r2d3.v2.js"></script><![endif]-->
<!--[if gte IE 9]><!-->
<script src="$mpath/lib/d3/d3.v2.js"></script>
<!--<![endif]-->

EOT;

$r2d3 = array(
    '#markup' => $script,
    '#type' => 'markup',
    '#weight' => -999,
);
drupal_add_html_head($r2d3, 'r2d3');

function pc_menu() {
    $items['admin/property-compendium'] = array(
        'title' => 'Property compendium',
        'access callback' => true,
        'description' => 'Manage property compendium',
        'page callback' => 'pc_overview_page',
        'file' => 'pc.admin.inc',
    );

    $items['admin/property-compendium/overview'] = array(
        'title' => 'Overview',
        'description' => 'Overview of properties',
        'file' => 'pc.admin.inc',
        'type' => MENU_DEFAULT_LOCAL_TASK
    );

    $items['admin/property-compendium/upload'] = array(
        'title' => 'Upload',
        'description' => 'Upload property compendium data',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('pc_upload_form'),
        'access callback' => true,
        'file' => 'pc.admin.inc',
        'type' => MENU_LOCAL_TASK
    );
		
    $items['property-portfolio/profiles/%pc_property'] = array(
        'title callback' => 'pc_title',
        'title arguments' => array(2),
        'page callback' => 'pc_property_page',
        'page arguments' => array(2),
				'menu_name' => 'navigation',
				'type' => MENU_NORMAL_ITEM,
        'file' => 'pc.pages.inc',
        'access callback' => true,
    );

    $items['property-portfolio/overview/summary'] = array(
        'title' => 'Portfolio Overview',
        'page callback' => 'pc_overview_summary',
        'file' => 'pc.pages.inc',
        'access callback' => true
    );

		$items['property-portfolio/overview'] = array(
        'title' => 'Portfolio Overview',
        'page callback' => "pc_overview",
        'file' => 'pc.pages.inc',
        'access callback' => true
    );

		$items['property-portfolio/centre-profiles'] = array(
	        'title' => 'Centre Profiles',
	        'page callback' => "pc_centre_profiles",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );
		
		// Regional Centre Profiles callbacks.
		
		$items['property-portfolio/centre-profiles/act'] = array(
	        'title' => 'Centre Profiles - Australian Capital Territory',
	        'page callback' => "pc_centre_profiles_act",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );
	
		$items['property-portfolio/centre-profiles/nsw'] = array(
	        'title' => 'Centre Profiles - New South Wales',
	        'page callback' => "pc_centre_profiles_nsw",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );
	
		$items['property-portfolio/centre-profiles/qld'] = array(
	        'title' => 'Centre Profiles - Queensland',
	        'page callback' => "pc_centre_profiles_qld",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );
	
		$items['property-portfolio/centre-profiles/sa'] = array(
	        'title' => 'Centre Profiles - South Australia',
	        'page callback' => "pc_centre_profiles_sa",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );
	
		$items['property-portfolio/centre-profiles/vic'] = array(
	        'title' => 'Centre Profiles - Victoria',
	        'page callback' => "pc_centre_profiles_vic",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );
	
		$items['property-portfolio/centre-profiles/wa'] = array(
	        'title' => 'Centre Profiles - Western Australia',
	        'page callback' => "pc_centre_profiles_wa",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );
	
		$items['property-portfolio/centre-profiles/nz'] = array(
	        'title' => 'Centre Profiles - New Zealand',
	        'page callback' => "pc_centre_profiles_nz",
	        'file' => 'pc.pages.inc',
	        'access callback' => true
	  );

    $items['property-portfolio/overview/portfolio-geographical-diversification'] = array(
        'title' => 'Portfolio Geographical Diversification',
        'page callback' => 'pc_pgd',
        'file' => 'pc.pages.inc',
        'access callback' => true
    );

    $items['property-portfolio/overview/joint-venture-partners'] = array(
        'title' => 'Joint Venture Partners',
        'page callback' => 'pc_jvp',
        'file' => 'pc.pages.inc',
        'access callback' => true
    );

    $items['property-portfolio/overview/lease-expiry-profile'] = array(
        'title' => 'Lease Expiry Profile',
        'page callback' => 'pc_lep',
        'file' => 'pc.pages.inc',
        'access callback' => true
    );

    $items['property-portfolio/overview/australia'] = array(
        'title' => 'Australia',
        'page callback' => 'pc_australia',
        'file' => 'pc.pages.inc',
        'access callback' => true
    );

    $items['property-portfolio/overview/new-zealand'] = array(
        'title' => 'New Zealand',
        'page callback' => 'pc_nz',
        'file' => 'pc.pages.inc',
        'access callback' => true
    );

    return $items;
}

/**
 * hook_load
 */
function pc_property_load($urititle) {
    $title = pc_title_from_urititle($urititle);
    $data = pc_process_sheet_from_title($title);
    return $data;
}


/**
 * Implements hook_theme.
 */
function pc_theme($existing, $type, $theme, $path) {
    return array(
        'pie' => array(
            'variables' => array('piedata' => array())
        ),
        'profile' => array(
            'variables' => array(
                'tables' => NULL
                , 'title' => NULL
                , 'chart' => NULL
                , 'centre_narrative' => NULL
            ),
            'template' => 'property'
        ),
				'briefcase-links' => array(
						'variables' => array('content' => NULL),
						'path' => drupal_get_path('module',  'wrt006') . '/theme',
						'file' => 'briefcase-links',
				),
    );
}

/**
 * pie theme function
 * Creates a pie chart
 * theme('pie', array('piedata' => array('values' => array(), 'legend' => array())));
 */
function theme_pie($variables) {

    drupal_add_js( drupal_get_path('module', 'pc') . '/js/pie.js', array('weight' => 99));
    $id = rand();

    $piedata = json_encode($variables['piedata']);

    return <<<EOT
<div class='piechart' id='pie$id'></div>
<script>
var piedata$id = $piedata;
drawPie(piedata$id, '#pie$id');
</script>
EOT;

}

/**
 * TODO: Write Documentation
 */
function pc_get_properties_from_region($region) {
	// Load the Property Compendium Excel file's Portfolio sheet.
	$file = file_load(variable_get('compendium', false));
	if($file == false) {
		// Error handeling
	}
	
  $filepath = drupal_realpath($file->uri);
  $ireader = PHPExcel_IOFactory::createReaderForFile($filepath);
  $ireader->setLoadSheetsOnly('Portfolio');
  $objPHPExcel = $ireader->load($filepath);
	
	// Get the active sheet.
	$sheet = $objPHPExcel->getSheet(0);
	
	// Read the Excel file.
	$rowmax = $sheet->getHighestRow();
	$pRange = 'C' . 1 . ':'. 'C' . $rowmax;
	$rowData = $sheet->rangeToArray( $pRange, NULL, TRUE, TRUE );
	
	$properties = array();
	
	$regions = array(
		'act' => 'Australian Capital Territory',
		'nsw' => 'New South Wales',
		'qld' => 'Queensland',
		'sa' => 'South Australia',
		'vic' => 'Victoria',
		'wa' => 'Western Australia',
		'nz' => 'New Zealand',
	);
	
	$record = 'none';
	
	foreach( $rowData as $row ){
		if( $row[0] == $regions[$region] )
			$record = $region;
		if( $row[0] == '' || $row[0] == ' ' )
			$record = 'none';
		
		$str = '-' . $record . '-';
		
		if( $str == '-' . $region . '-' )
			array_push($properties, $row[0]);
	}
	
	array_shift( $properties );
	
	if( $region == 'nz' ){
		array_shift( $properties );
		array_shift( $properties );
	}
	
	return $properties;
}

function pc_process_sheet_from_title($title) {

    $cachefile = pc_cache_file($title);
    $make_assoc = true;

    if (file_exists($cachefile)) {
        return json_decode(file_get_contents($cachefile), $make_assoc);
    } else {
        $file = file_load(variable_get('compendium', false));
        $filepath = drupal_realpath($file->uri);
        $ireader = PHPExcel_IOFactory::createReaderForFile($filepath);
        $ireader->setLoadSheetsOnly($title);
        $objPHPExcel = $ireader->load($filepath);
        $sheet = $objPHPExcel->getSheetByName($title);
        $data = pc_process_sheet($sheet);
        file_put_contents($cachefile, json_encode($data));
        return $data;
    }
}

function pc_process_sheet($sheet) {
    $rowmax = $sheet->getHighestRow();
    $parse = new Parse();
    $title = $sheet->getTitle();
    $pRange = COL_START . 1 . ':'. COL_END . $rowmax;
    $nullValue = NULL;
    $calculateFormulas = TRUE;
    $formatData = TRUE;
    $rowData = $sheet->rangeToArray(
        $pRange
        , $nullValue
        , $calculateFormulas
        , $formatData);
    foreach ( $rowData as $row ) {
        $parse->processRow($row);
    }
    $data = $parse->propertyData();
    $data['title'] = $title;

    return $data;
}

/**
 * Callbacks
 */
function pc_title($pc_property) {
    return $pc_property['title'];
}

/**
 * Helpers
 */

/**
 * function is idepotent so can call repeatedly on urititle and
 * title without any issues.
 */
function pc_title_from_urititle($urititle) {
    return str_replace('-', ' ', $urititle);
}

function pc_urititle_from_title($title) {
    return str_replace(' ', '-', $title);
}

function pc_piedata_from_graphdata($graphdata) {
    return array(
        'values' => array_values($graphdata),
        'legend' => array_keys($graphdata),
    );
}

function pc_cache_dirpath() {
    $dir = drupal_realpath('public://'. PC_CACHE_DIRNAME);
    file_prepare_directory($dir, FILE_MODIFY_PERMISSIONS | FILE_CREATE_DIRECTORY );
    return $dir;
}

function pc_cache_file($urititle) {
    $title = pc_title_from_urititle($urititle);
    $filename = md5($title).'.json';
    return pc_cache_dirpath()."/$filename";
}

function pc_delete_cache() {
    $cachefiles = glob( pc_cache_dirpath() . '/*');
    array_map('unlink', $cachefiles);
}

function pc_summary_data() {
    $file = file_load(variable_get('compendium', false));
    $filepath = drupal_realpath($file->uri);
    $ireader = PHPExcel_IOFactory::createReaderForFile($filepath);
    $ireader->setLoadSheetsOnly(array('Control' , 'Portfolio'));
    $objPHPExcel = $ireader->load($filepath);
    $sheet = $objPHPExcel->getSheet(PC_OVERVIEW_SHEET);

    $rows = $sheet->rangeToArray(PC_EXCEL_SUMMARY,
        NULL,
        TRUE,
        TRUE);

    $sheet = $objPHPExcel->getSheet(PC_CONTROL_SHEET);

    $period = $sheet->rangeToArray(PC_EXCEL_PERIOD,
        NULL,
        TRUE,
        TRUE);

    return array(
        'rows' => $rows
        , 'period' => $period[0][0]
    );
}

function pc_render_array_from_summary_data($summary_data) {
    $header = array('At '.$summary_data['period'], 'Australia', 'New Zealand', 'Total');

    return array(
        'table' => array(
            '#theme' => 'table',
            '#header' => $header,
            '#rows' => $summary_data['rows'],
            '#prefix' => '<div class="portfolio">',
            '#suffix' => '</div>',
        )
    );
}

function pc_pgd_data() {

    $file = file_load(variable_get('compendium', false));
    $filepath = drupal_realpath($file->uri);
    $ireader = PHPExcel_IOFactory::createReaderForFile($filepath);
    $ireader->setLoadSheetsOnly(array('Control' , 'Portfolio'));
    $objPHPExcel = $ireader->load($filepath);
    $sheet = $objPHPExcel->getSheet(PC_OVERVIEW_SHEET);

    $gla = $sheet->rangeToArray(PC_EXCEL_GROSS_LETTABLE_AREA,
        NULL,
        TRUE,
        FALSE);

    $av = $sheet->rangeToArray(PC_EXCEL_ASSET_VALUE,
        NULL,
        TRUE,
        FALSE);

    $nop = $sheet->rangeToArray(PC_EXCEL_NET_OPERATING_INCOME,
        NULL,
        TRUE,
        FALSE);

    return array(
        'Gross Lettable Area' => $gla,
        'Asset Value' => $av,
        'Net Operating Income' => $nop
    );
}

function pc_fullstate_from_short($stateabbr) {
    $states = array(
        'NSW' => 'New South Wales',
        'VIC' => 'Victoria',
        'QLD' => 'Queensland',
        'SA' => 'South Australia',
        'WA' => 'Western Australia',
        'ACT' => 'Australian Capital Territory',
        'NZ' => 'New Zealand'
    );

    return $states[$stateabbr];
}

function pc_excel_range($range, $format = false) {

    $file = file_load(variable_get('compendium', false));
    $filepath = drupal_realpath($file->uri);
    $ireader = PHPExcel_IOFactory::createReaderForFile($filepath);
    $ireader->setLoadSheetsOnly(array('Control' , 'Portfolio'));
    $objPHPExcel = $ireader->load($filepath);
    $sheet = $objPHPExcel->getSheet(PC_OVERVIEW_SHEET);

    $rows = $sheet->rangeToArray($range,
        NULL,
        TRUE,
        $format);

    return $rows;
}

function pc_piedata_from_rows($rows) {

    $piedata = array();
    $piedata['legend'] = array();
    $piedata['values'] = array();

    foreach($rows as $row) {
        $piedata['legend'][] = $row[0];
        $piedata['values'][] = preg_replace('/[^\d\.]/', '', end($row));
    }

    return $piedata;
}
